apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webpage-ingress
  namespace: plandera-webpage-staging
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  # New domain - plandera.com
  - host: staging-www.plandera.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webpage
            port:
              number: 3000
  # Old domain - streamline-scheduler.com (redirect to rebranded page)
  - host: staging.streamline-scheduler.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webpage
            port:
              number: 3000
  tls:
  - hosts:
    - staging-www.plandera.com
    - staging.streamline-scheduler.com
    secretName: staging-webpage-tls

