apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webpage-ingress
  namespace: planera-webpage-production
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: www.planera.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webpage
            port:
              number: 3000
  - host: planera.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webpage
            port:
              number: 3000
  tls:
  - hosts:
    - www.planera.app
    - planera.app
    secretName: production-webpage-tls

